# Generated by Django 4.0.3 on 2022-05-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubstaff',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='clubstaff',
            old_name='user_id',
            new_name='user',
        ),
    ]
