# Generated by Django 4.0.3 on 2022-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_club_id_clubstaff_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubstaff',
            old_name='club',
            new_name='club_id',
        ),
        migrations.RenameField(
            model_name='clubstaff',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
